# Generated by Django 4.1.7 on 2023-02-17 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_person_ipaddress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='ipaddress',
        ),
    ]
