# Generated by Django 4.1.7 on 2023-03-11 03:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_remove_person_ipaddress'),
    ]

    operations = [
        migrations.CreateModel(
            name='drug',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('d_id', models.IntegerField()),
                ('name', models.CharField(max_length=50)),
                ('hospitalDeapartment', models.CharField(max_length=50)),
                ('appearance', models.CharField(max_length=100)),
                ('indications', models.CharField(max_length=50)),
                ('sideEffect', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='interactingDrugs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('i_id', models.IntegerField()),
                ('level', models.CharField(max_length=20)),
                ('cause', models.CharField(max_length=100)),
                ('drug', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.drug')),
            ],
        ),
        migrations.CreateModel(
            name='record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('r_id', models.IntegerField()),
                ('dosage', models.IntegerField()),
                ('timeSlot_1', models.TimeField(default='09:00:00')),
                ('timeSlot_2', models.TimeField(default='12:00:00')),
                ('timeSlot_3', models.TimeField(default='18:00:00')),
                ('drug_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='base.drug')),
            ],
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('u_id', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='person',
        ),
        migrations.AddField(
            model_name='record',
            name='u_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.user'),
        ),
        migrations.AddField(
            model_name='interactingdrugs',
            name='r_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.record'),
        ),
    ]
