# Generated by Django 4.1.7 on 2023-03-11 03:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_drug_interactingdrugs_record_user_delete_person_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drug',
            name='d_id',
        ),
        migrations.RemoveField(
            model_name='interactingdrugs',
            name='i_id',
        ),
        migrations.RemoveField(
            model_name='record',
            name='r_id',
        ),
        migrations.RemoveField(
            model_name='user',
            name='u_id',
        ),
        migrations.AddField(
            model_name='user',
            name='u_name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='record',
            name='drug_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='records', to='base.drug'),
        ),
    ]
