# Generated by Django 4.1.7 on 2023-03-11 03:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_remove_drug_d_id_remove_interactingdrugs_i_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='interactingdrugs',
            old_name='r_id',
            new_name='record',
        ),
        migrations.RenameField(
            model_name='record',
            old_name='drug_id',
            new_name='drug',
        ),
        migrations.RenameField(
            model_name='record',
            old_name='u_id',
            new_name='user',
        ),
    ]
