# Generated by Django 4.1.7 on 2023-03-11 04:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_rename_r_id_interactingdrugs_record_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interactingdrugs',
            name='drug',
        ),
        migrations.RemoveField(
            model_name='interactingdrugs',
            name='record',
        ),
        migrations.AlterField(
            model_name='interactingdrugs',
            name='cause',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='interactingdrugs',
            name='level',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='base.user'),
        ),
    ]
