# Generated by Django 4.1.7 on 2023-03-11 04:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_remove_interactingdrugs_drug_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='interactingDrugs',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='records', to='base.interactingdrugs'),
        ),
    ]
