# Generated by Django 4.1.7 on 2023-03-11 05:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_alter_interactingdrugs_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='drug',
        ),
        migrations.RemoveField(
            model_name='record',
            name='interactingDrugs',
        ),
        migrations.RemoveField(
            model_name='record',
            name='user',
        ),
        migrations.AddField(
            model_name='drug',
            name='record',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='drugs', to='base.record'),
        ),
        migrations.AddField(
            model_name='interactingdrugs',
            name='record',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='interactingDrugs', to='base.record'),
        ),
        migrations.AlterField(
            model_name='interactingdrugs',
            name='cause',
            field=models.CharField(max_length=100),
        ),
    ]
