# Generated by Django 4.1.7 on 2023-03-11 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_remove_record_drug_remove_record_interactingdrugs_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interactingdrugs',
            name='cause',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
