# Generated by Django 4.1.7 on 2023-03-18 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_alter_interactingdrugs_cause'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='u_name',
            new_name='name_eng',
        ),
        migrations.AddField(
            model_name='drug',
            name='hospitalName',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='record',
            name='notification_remind',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='record',
            name='notification_repeat',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='record',
            name='notification_status',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='record',
            name='notification_volume',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='record',
            name='return_date',
            field=models.DateField(default=0),
        ),
        migrations.AddField(
            model_name='record',
            name='return_left',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='record',
            name='return_repeat',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='record',
            name='return_status',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='record',
            name='stock',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='name_man',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='drug',
            name='hospitalDeapartment',
            field=models.CharField(default='', max_length=50),
        ),
    ]
