# Generated by Django 4.1.7 on 2023-03-18 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_rename_u_name_user_name_eng_drug_hospitalname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='stock',
            field=models.IntegerField(default=0),
        ),
    ]
