# Generated by Django 4.1.7 on 2023-03-18 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_alter_record_stock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='name_man',
        ),
    ]
