# Generated by Django 4.1.7 on 2023-03-18 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_remove_user_name_man'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='u_name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
