# Generated by Django 4.1.7 on 2023-03-18 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_user_u_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='u_name',
            new_name='name_man',
        ),
    ]
