# Generated by Django 4.1.7 on 2023-03-18 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_rename_u_name_user_name_man'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='stck',
            field=models.IntegerField(default=0),
        ),
    ]
