# Generated by Django 4.1.7 on 2023-03-18 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0018_remove_record_stck'),
    ]

    operations = [
        migrations.RenameField(
            model_name='record',
            old_name='stock',
            new_name='stck',
        ),
    ]
