# Generated by Django 4.1.7 on 2023-03-18 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0020_remove_record_stck'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='stock',
            field=models.IntegerField(default=0),
        ),
    ]
