# Generated by Django 4.1.7 on 2023-03-18 06:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0021_record_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='return_status',
            field=models.IntegerField(default=0),
        ),
    ]
