# Generated by Django 4.1.7 on 2023-03-18 06:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0022_alter_record_return_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='return_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='record',
            name='return_left',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='record',
            name='return_repeat',
            field=models.IntegerField(default=0),
        ),
    ]
