# Generated by Django 4.1.7 on 2023-03-26 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0024_socialaccount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='name_eng',
        ),
        migrations.RemoveField(
            model_name='user',
            name='name_man',
        ),
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='first_name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='user',
            name='last_name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(default='', max_length=50),
        ),
    ]
