# Generated by Django 4.1.7 on 2023-04-16 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0025_remove_user_name_eng_remove_user_name_man_user_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='notification_volume',
        ),
        migrations.AddField(
            model_name='record',
            name='ondemand',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='record',
            name='timings_1',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='record',
            name='timings_2',
            field=models.IntegerField(default=0),
        ),
    ]
