# Generated by Django 4.1.7 on 2023-04-16 07:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0026_remove_record_notification_volume_record_ondemand_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='notification_startDate',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
