# Generated by Django 4.1.7 on 2023-04-16 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0027_record_notification_startdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='frequency',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='record',
            name='position',
            field=models.IntegerField(default=1),
        ),
    ]
