# Generated by Django 4.1.7 on 2023-04-30 06:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0028_record_frequency_record_position'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='timeSlot_1',
        ),
        migrations.RemoveField(
            model_name='record',
            name='timeSlot_2',
        ),
        migrations.RemoveField(
            model_name='record',
            name='timeSlot_3',
        ),
        migrations.CreateModel(
            name='timeslots',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timeslot', models.TimeField(default='09:00:00')),
                ('record', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='timeslots', to='base.record')),
            ],
        ),
    ]
