# Generated by Django 4.1.7 on 2023-04-30 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0029_remove_record_timeslot_1_remove_record_timeslot_2_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='drug',
            old_name='record',
            new_name='rid',
        ),
        migrations.RenameField(
            model_name='interactingdrugs',
            old_name='record',
            new_name='rid',
        ),
    ]
