# Generated by Django 4.1.7 on 2023-04-30 08:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0030_rename_record_drug_rid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drug',
            name='rid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='drugs', to='base.record'),
        ),
        migrations.AlterField(
            model_name='interactingdrugs',
            name='rid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='interactingDrugs', to='base.record'),
        ),
    ]
