# Generated by Django 4.1.7 on 2023-04-30 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0031_alter_drug_rid_alter_interactingdrugs_rid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drug',
            name='hospitalDeapartment',
        ),
        migrations.RemoveField(
            model_name='drug',
            name='hospitalName',
        ),
        migrations.AddField(
            model_name='record',
            name='comment',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='record',
            name='hospitalDeapartment',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='record',
            name='hospitalName',
            field=models.CharField(default='', max_length=50),
        ),
    ]
