# Generated by Django 4.1.7 on 2023-05-06 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0032_remove_drug_hospitaldeapartment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='interactingdrugs',
            name='name',
            field=models.CharField(default=' ', max_length=20),
        ),
        migrations.AlterField(
            model_name='interactingdrugs',
            name='cause',
            field=models.CharField(default=' ', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='interactingdrugs',
            name='level',
            field=models.CharField(default=' ', max_length=20),
        ),
    ]
