# Generated by Django 4.1.7 on 2023-05-07 06:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0033_interactingdrugs_name_alter_interactingdrugs_cause_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='timings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timing', models.IntegerField(default=0)),
                ('record', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='timings', to='base.record')),
            ],
        ),
    ]
