# Generated by Django 4.1.7 on 2023-05-22 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0035_remove_record_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='record',
            old_name='hospitalDeapartment',
            new_name='hospitalDepartment',
        ),
    ]
