# Generated by Django 4.1.7 on 2023-06-22 09:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0036_rename_hospitaldeapartment_record_hospitaldepartment'),
    ]

    operations = [
        migrations.CreateModel(
            name='historyRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today)),
                ('timeslots', models.TimeField(default='09:00:00')),
                ('drug_id', models.IntegerField(default=0)),
                ('drug_name', models.CharField(default=' ', max_length=20)),
                ('dosage', models.IntegerField(default=0)),
                ('status', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='reminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drug_id', models.IntegerField(default=0)),
                ('drug_name', models.CharField(default=' ', max_length=20)),
                ('timeslots', models.TimeField(default='09:00:00')),
                ('dosage', models.IntegerField(default=0)),
                ('position', models.IntegerField(default=0)),
                ('stock', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='record',
            name='hospitalextension',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='record',
            name='hospitalphone',
            field=models.CharField(default='', max_length=50),
        ),
    ]
