# Generated by Django 4.1.7 on 2023-06-22 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0037_historyrecord_reminder_record_hospitalextension_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historyrecord',
            old_name='timeslots',
            new_name='timeSlot',
        ),
        migrations.RenameField(
            model_name='reminder',
            old_name='timeslots',
            new_name='timeSlot',
        ),
    ]
