# Generated by Django 4.1.7 on 2023-06-26 12:58

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0038_rename_timeslots_historyrecord_timeslot_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='historyRecord',
        ),
        migrations.RemoveField(
            model_name='reminder',
            name='dosage',
        ),
        migrations.RemoveField(
            model_name='reminder',
            name='position',
        ),
        migrations.RemoveField(
            model_name='reminder',
            name='stock',
        ),
        migrations.AddField(
            model_name='reminder',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='reminder',
            name='rid',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='base.record'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reminder',
            name='status',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='drug',
            name='rid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drugs', to='base.record'),
        ),
        migrations.AlterField(
            model_name='interactingdrugs',
            name='rid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactingDrugs', to='base.record'),
        ),
    ]
