# Generated by Django 4.1.7 on 2023-06-27 10:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0040_alter_timeslots_record'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeslots',
            name='record',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='timeslots', to='base.record'),
        ),
    ]
