# Generated by Django 4.1.7 on 2023-06-27 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0041_alter_timeslots_record'),
    ]

    operations = [
        migrations.RenameField(
            model_name='timeslots',
            old_name='record',
            new_name='rid',
        ),
        migrations.RenameField(
            model_name='timings',
            old_name='record',
            new_name='rid',
        ),
    ]
